# Default values for api-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

## 设置默认的 image、imageTag 和 imagePullPolicy。
image:
  repository: registry.cn-shanghai.aliyuncs.com/c7n/choerodon-front-pro
  tag: ~
  pullPolicy: IfNotPresent

# preJob:
#   preConfig:
#     mysql:
#       host: localhost
#       port: 3306
#       username: choerodon
#       password: 123456
#       dbname: iam_service

## service 相关设置
## ref: http://kubernetes.io/docs/user-guide/services/
##
service:
  # 是否启用 service 暴露本服务
  enabled: true
  # Service 名称
  name: hzero-front
  # Service 类型
  type: ClusterIP
  # 指定 service 的 clusterIP
  clusterIP: ~
  # 端口设置
  ports:
    # 服务端口
    http:
      port: 80
      nodePort: 30154
  ## externalIPs 设置
  # externalIPs:
  #   - externalIp1
  annotations: {}

## Ingress 相关配置
## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
##
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
  path: /
  host: choerodon.example.com
  tls: []
  # - secretName: choerodon-example-tls
  #   hosts:
  #   - choerodon.example.com

env:
  open:
    BUILD_BASE_PATH: /
    BUILD_PUBLIC_URL: /
    BUILD_WEBSOCKET_HOST: ws://ws.hft.jajabjbj.top
    BUILD_BPM_HOST: http://bpm.hft.jajabjbj.top
    BUILD_CLIENT_ID: localhost
    BUILD_API_HOST: http://backend.hft.jajabjbj.top  # http://192.168.12.101:8080/
    BUILD_CUSTOMIZE_ICON_NAME: icon-font
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
    BUILD_PLATFORM_VERSION: SAAS
    IM_ENABLE: BUILD_IM_ENABLE # // im是否启用，true/false
    IM_WEBSOCKET_HOST: BUILD_IM_WEBSOCKET_HOST # // im websocket 地址
    TRACE_LOG_ENABLE: BUILD_TRACE_LOG_ENABLE # // TraceLog日志追溯分析是否启用，true/false
    CUSTOMIZE_ICON_NAME: BUILD_CUSTOMIZE_ICON_NAME # // 客制化的iconfont font family 名称
#    TOP_MENU_LABELS: HZERO_MENU
#    TOP_MENU_UNION_LABEL: true
#    BUILD_TOP_MENU_LABELS: HZERO_MENU
#    BUILD_TOP_MENU_UNION_LABEL: true

# 是否收集日志至EFK
logs:
  enabled: false
  # 日志收集格式
  parser: nginx

## 资源请求和限制相关配置
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  limits:
    # cpu: 100m
    memory: 128Mi
  requests:
    # cpu: 100m
    memory: 128Mi

